name: Deployment

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  plan-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Plan changes
        id: chalk-plan
        run: |
          {
            echo 'plan-output<<EOF'
            echo "Here is some very long, potentially multiline output"
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Repeat back plan
        run: |
          echo ${{ steps.chalk-plan.outputs.plan-output }}

  apply-dev:
    runs-on: ubuntu-latest
    needs: plan-dev
    environment: dev # successfully running this job will create a deployment for this environment
    steps:
      - name: Plan changes
        id: chalk-plan
        run: |
          echo "Now I actually apply changes"

